[2023-09-19T09:29:45.839+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: udac_example_dag.stage_events_to_redshift_task manual__2023-09-19T09:29:43.302361+00:00 [queued]>
[2023-09-19T09:29:45.844+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: udac_example_dag.stage_events_to_redshift_task manual__2023-09-19T09:29:43.302361+00:00 [queued]>
[2023-09-19T09:29:45.845+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-19T09:29:45.857+0000] {taskinstance.py:1382} INFO - Executing <Task(StageToRedshiftOperator): stage_events_to_redshift_task> on 2023-09-19 09:29:43.302361+00:00
[2023-09-19T09:29:45.862+0000] {standard_task_runner.py:57} INFO - Started process 113 to run task
[2023-09-19T09:29:45.864+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'udac_example_dag', 'stage_events_to_redshift_task', 'manual__2023-09-19T09:29:43.302361+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp5a0wb_p_']
[2023-09-19T09:29:45.866+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask stage_events_to_redshift_task
[2023-09-19T09:29:45.901+0000] {task_command.py:415} INFO - Running <TaskInstance: udac_example_dag.stage_events_to_redshift_task manual__2023-09-19T09:29:43.302361+00:00 [running]> on host cd9223bba8c3
[2023-09-19T09:29:45.947+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kstine' AIRFLOW_CTX_DAG_ID='udac_example_dag' AIRFLOW_CTX_TASK_ID='stage_events_to_redshift_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T09:29:43.302361+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-19T09:29:43.302361+00:00'
[2023-09-19T09:29:45.948+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    hook = PostgresHook(self.postgres_conn_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'postgres_conn_id'
[2023-09-19T09:29:45.953+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=stage_events_to_redshift_task, execution_date=20230919T092943, start_date=20230919T092945, end_date=20230919T092945
[2023-09-19T09:29:45.970+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task stage_events_to_redshift_task ('StageToRedshiftOperator' object has no attribute 'postgres_conn_id'; 113)
[2023-09-19T09:29:45.996+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T09:29:46.033+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
